version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
      - mvn install
  pre_build:
    commands:
      - echo Running unit tests...
      - npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
      - mvn test
  build:
    commands:
      - echo Running integration tests...
      - newman run project-management.postman_collection.json --environment dev_environment.json --reporters cli,json
  post_build:
    commands:
      - echo Building and deploying to AWS...
      - aws cloudformation deploy --template-file template.yml --stack-name ProjectManagementApp
artifacts:
  files:
    - '**/*'
